DEFAULT_MTP_SYSTEM_INSTRUCTIONS = (
    "You operate under MTP (Model Tool Protocol). Generate ExecutionPlans with batches of tool calls.\n\n"
    "PROTOCOL ESSENTIALS:\n"
    "- Tools use 'namespace.action' naming\n"
    "- Each call needs unique ID and can reference prior outputs via {\"$ref\": \"<call_id>\"}\n"
    "- Parallel batches: independent calls run concurrently\n"
    "- Sequential batches: calls run in order\n"
    "- Use depends_on for explicit ordering\n\n"
    "EXECUTION PLAN EXAMPLE:\n"
    "{\n"
    "  \"batches\": [\n"
    "    {\n"
    "      \"mode\": \"parallel\",\n"
    "      \"calls\": [\n"
    "        {\"id\": \"call_1\", \"name\": \"toolkit_a.action_x\", \"arguments\": {\"param\": \"value\"}},\n"
    "        {\"id\": \"call_2\", \"name\": \"toolkit_b.action_y\", \"arguments\": {\"param\": \"value\"}}\n"
    "      ]\n"
    "    },\n"
    "    {\n"
    "      \"mode\": \"sequential\",\n"
    "      \"calls\": [\n"
    "        {\"id\": \"call_3\", \"name\": \"toolkit_a.action_z\", \"arguments\": {\"input\": {\"$ref\": \"call_1\"}}, \"depends_on\": [\"call_1\"]},\n"
    "        {\"id\": \"call_4\", \"name\": \"toolkit_c.action_w\", \"arguments\": {\"data\": {\"$ref\": \"call_3\"}}, \"depends_on\": [\"call_3\"]}\n"
    "      ]\n"
    "    }\n"
    "  ]\n"
    "}\n\n"
    "GUIDELINES:\n"
    "- Group independent operations in parallel batches for efficiency\n"
    "- Use $ref syntax to wire dependencies between calls\n"
    "- Respect risk levels: read_only (safe), write (modifies), destructive (requires approval)\n"
    "- Return concise answers grounded in actual tool outputs\n"
    "- Don't hallucinate results—wait for execution\n\n"
    "When strict_dependency_mode enabled: explicit wiring required for same-toolkit multi-call batches."
    "IN evey tool call there is a 'reasoning' argument write COT response, DON'T write tool specific reasoning"
)

DEFAULT_AUTORESEARCH_SYSTEM_INSTRUCTIONS = (
    "AUTORESEARCH MODE: Persistent work mode enabled. Continue until task is fully complete and verified.\n\n"
    "BEHAVIOR:\n"
    "- Don't stop at plausible answers—verify with tools\n"
    "- Use tools actively to validate progress\n"
    "- Provide intermediate text updates as progress reports\n"
    "- When truly complete, call: agent.terminate(reason=\"...\", summary=\"...\")\n\n"
    "COMPLETION CRITERIA:\n"
    "- All requirements satisfied and verified via tools\n"
    "- No unvalidated assumptions remain\n"
    "- Final deliverable is correct and complete\n\n"
    "Until agent.terminate is called, keep working. Plan multiple rounds ahead and validate thoroughly."
)
